export default {
    PEAK: 'PEAK',
    MOUNTAIN: 'MOUNTAIN',
    FOREST: 'FOREST',
    BEACH: 'BEACH',
    WATERFALL: 'WATERFAL',
    LAKE: 'LAKE',
    MUSEUM: 'MUSEUM',
    RECREATIONAL_PARK: 'RECREATIONAL_PARK',
    TOURIST_VILLAGE: 'TOURIST_VILLAGE',
    OTHERS: 'OTHERS',
};
